import { create } from 'zustand';
import type { 
  Candidate, 
  VotingState, 
  VoteConfirmation, 
  ElectionParams,
  EncryptionResult 
} from '../types';
import type { 
  ZKProofData, 
  ZKProofGenerationStatus, 
  PublicVerificationData
} from '../types/zkProof';
import { loadWasmModule } from '../wasmModule';
import { 
  generateZKProof, 
  verifyCompleteZKProofWithDetails,
  generatePublicVerificationData 
} from '../utils/zkProof';
import { generateDeterministicKeys } from '../utils/deterministicKeyGen';
import { generateCommitmentParameters } from '../utils/commitmentScheme';
import { performSecurityChecks, validateProofSubmissionReadiness } from '../utils/validation';
import { zkProofApi } from '../utils/zkProofApi';
import { CANDIDATE_CONFIG, API_ENDPOINTS, ERROR_MESSAGES } from '../utils/constants';
import { submitVote, setupElection } from '../wasmModule';

interface VotingStore extends VotingState {
  // Existing methods
  loadCandidates: () => Promise<void>;
  selectCandidate: (candidate: Candidate) => void;
  clearSelection: () => void;
  encryptSelectedVote: () => Promise<EncryptionResult>;
  submitVote: (voterId: string) => Promise<void>;
  resetVoting: () => void;
  setError: (error: string | null) => void;
  initializeElectionParams: () => Promise<ElectionParams>;
  
  // ZK Proof methods
  zkProofStatus: ZKProofGenerationStatus;
  zkProof: ZKProofData | null;
  publicVerificationData: PublicVerificationData | null;
  
  generateVoteZKProof: (vote: number[], voterID: string) => Promise<ZKProofData>;
  verifyOwnProof: (proof: ZKProofData) => Promise<boolean>;
  getPublicVerificationData: () => PublicVerificationData | null;
  enforceSignleGeneration: () => void;
  setZKProofStatus: (status: ZKProofGenerationStatus) => void;
}

const mockCandidates: Candidate[] = [
  {
    id: 1,
    name: 'Alice Johnson',
    photo: '/assets/candidate1.jpg',
    party: 'Progressive Party',
    description: 'Experienced leader focused on education and healthcare reform.',
  },
  {
    id: 2,
    name: 'Bob Smith',
    photo: '/assets/candidate2.jpg',
    party: 'Unity Party',
    description: 'Business leader committed to economic growth and job creation.',
  },
  {
    id: 3,
    name: 'Carol Davis',
    photo: '/assets/candidate3.jpg',
    party: 'Green Alliance',
    description: 'Environmental advocate working for sustainable development.',
  },
  {
    id: 4,
    name: 'David Wilson',
    photo: '/assets/candidate4.jpg',
    party: 'Independent',
    description: 'Community organizer focused on local issues and transparency.',
  },
];

const getBackendUrl = () => {
  return import.meta.env.VITE_BACKEND_URL || 'http://localhost:3000';
};

// Helper functions for election operations
const initializeElection = async (): Promise<ElectionParams> => {
  try {
    await loadWasmModule();
    const params = await setupElection();
    return {
      n: params.n,
      h: params.h,
      ska: params.ska || new Uint8Array()
    };
  } catch (error) {
    throw new Error(`Election initialization failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
};

// Helper to generate vote array for a specific candidate
const generateVoteArray = (candidateId: number, totalCandidates: number): number[] => {
  const voteArray = new Array(totalCandidates).fill(0);
  if (candidateId >= 1 && candidateId <= totalCandidates) {
    voteArray[candidateId - 1] = 1; // 1-indexed to 0-indexed
  }
  return voteArray;
};

const encryptVote = async (
  candidateId: number,
  totalCandidates: number,
  electionParams: ElectionParams
): Promise<EncryptionResult> => {
  try {
    const voteArray = generateVoteArray(candidateId, totalCandidates);
    
    // Use WASM module to submit vote (this prepares encryption internally)
    await submitVote(candidateId, 'voter-id', {
      n: electionParams.n,
      h: electionParams.h,
      ska: electionParams.ska
    });
      return {
      encryptedVote: new Uint8Array(voteArray.map(v => v)),
      auxiliaryKey: new Uint8Array() // Would be generated by WASM module
    };
  } catch (error) {
    throw new Error(`Vote encryption failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
};

export const useVotingStore = create<VotingStore>((set, get) => ({
  candidates: [],
  selectedCandidate: null,
  isVoting: false,
  hasVoted: false,
  encryptedVote: null,
  voteConfirmation: null,
  error: null,
  isLoading: false,
    // ZK Proof state
  zkProofStatus: {
    status: 'idle',
    progress: 0,
    currentStep: 'initializing',
    wasmStatus: 'loading'
  },
  zkProof: null,
  publicVerificationData: null,

  loadCandidates: async () => {
    set({ isLoading: true, error: null });

    try {
      // Try to fetch candidates from backend, fall back to mock data
      try {
        const response = await fetch(`${getBackendUrl()}${API_ENDPOINTS.CANDIDATES}`);
        if (response.ok) {
          const candidates = await response.json();
          set({ candidates, isLoading: false });
          return;
        }
      } catch (error) {
        console.warn('Failed to fetch candidates from backend, using mock data');
      }

      // Use mock candidates as fallback
      set({ candidates: mockCandidates, isLoading: false });
    } catch (error) {
      set({
        error: 'Failed to load candidates',
        isLoading: false,
      });
    }
  },

  selectCandidate: (candidate: Candidate) => {
    if (get().hasVoted) {
      set({ error: ERROR_MESSAGES.ALREADY_VOTED });
      return;
    }

    set({ 
      selectedCandidate: candidate,
      error: null,
    });
    
    console.log('Selected candidate:', candidate.name);
  },

  clearSelection: () => {
    set({ 
      selectedCandidate: null,
      encryptedVote: null,
      error: null,
    });
  },

  initializeElectionParams: async (): Promise<ElectionParams> => {
    try {
      set({ isLoading: true, error: null });
      const params = await initializeElection();
      set({ isLoading: false });
      return params;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : ERROR_MESSAGES.WASM_LOAD_ERROR;
      set({ 
        error: errorMessage,
        isLoading: false,
      });
      throw error;
    }
  },

  encryptSelectedVote: async (): Promise<EncryptionResult> => {
    const { selectedCandidate } = get();
    
    if (!selectedCandidate) {
      throw new Error('No candidate selected');
    }

    set({ isLoading: true, error: null });

    try {
      // Initialize election parameters
      const electionParams = await get().initializeElectionParams();
      
      // Encrypt the vote
      const encryptionResult = await encryptVote(
        selectedCandidate.id,
        CANDIDATE_CONFIG.TOTAL_CANDIDATES,
        electionParams
      );

      set({ 
        encryptedVote: encryptionResult.encryptedVote,
        isLoading: false,
      });

      console.log('Vote encrypted successfully for candidate:', selectedCandidate.name);
      return encryptionResult;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : ERROR_MESSAGES.ENCRYPTION_ERROR;
      set({ 
        error: errorMessage,
        isLoading: false,
      });
      throw error;
    }
  },

  submitVote: async (voterId: string) => {
    const { selectedCandidate } = get();
    
    if (!selectedCandidate) {
      set({ error: 'No candidate selected' });
      return;
    }

    if (get().hasVoted) {
      set({ error: ERROR_MESSAGES.ALREADY_VOTED });
      return;
    }

    set({ isVoting: true, error: null });    try {
      // Initialize election parameters
      const electionParams = await get().initializeElectionParams();
      
      // Submit the vote using the WASM module
      await submitVote(selectedCandidate.id, voterId, {
        n: electionParams.n,
        h: electionParams.h,
        ska: electionParams.ska
      });

      // Generate vote confirmation using ZK proof
      const confirmation: VoteConfirmation = {
        voterId,
        candidateName: selectedCandidate.name,
        timestamp: new Date(),
        transactionHash: `tx_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        zkProofId: get().zkProof?.id || 'pending',
        verificationCode: get().publicVerificationData?.verificationCode || 'pending',
        isZKProofValid: get().zkProof !== null,
        zkProofSummary: {
          rangeProofValid: get().zkProof !== null,
          sumProofValid: get().zkProof !== null,
          generationProofValid: get().zkProof !== null,
          mathematicallySound: get().zkProof !== null,
        }
      };

      set({
        isVoting: false,
        hasVoted: true,
        voteConfirmation: confirmation,
        error: null,
      });

      console.log('Vote submitted successfully for:', selectedCandidate.name);
      console.log('Transaction hash:', confirmation.transactionHash);
      console.log('ZK Proof verification code:', confirmation.verificationCode);
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : ERROR_MESSAGES.VOTE_SUBMISSION_ERROR;
      set({
        isVoting: false,
        error: errorMessage,
      });
      throw error;
    }
  },

  resetVoting: () => {
    set({      selectedCandidate: null,
      isVoting: false,
      hasVoted: false,
      encryptedVote: null,
      voteConfirmation: null,
      error: null,
      isLoading: false,
    });  },
  
  setError: (error: string | null) => {
    set({ error });
  },  // ZK Proof methods
  generateVoteZKProof: async (vote: number[], voterID: string): Promise<ZKProofData> => {
    try {
      console.log('Starting ZK proof generation with:', { vote, voterID });
      
      // First, ensure WASM module is loaded and ready
      console.log('Loading WASM module...');
      await loadWasmModule();
      console.log('WASM module loaded successfully');
      
      // Security checks
      const securityCheck = await performSecurityChecks(
        await crypto.subtle.digest('SHA-256', new TextEncoder().encode(voterID)).then(
          buffer => Array.from(new Uint8Array(buffer)).map(b => b.toString(16).padStart(2, '0')).join('')
        ),
        'default-election'
      );
      
      console.log('Security check result:', securityCheck);
      
      if (!securityCheck.canProceed) {
        throw new Error(`Security check failed: ${securityCheck.securityReport.recommendations.join(', ')}`);
      }
        console.log('Generating deterministic keys...');
      
      // Generate commitment parameters first
      const commitmentParams = await generateCommitmentParameters('default-seed-2025');
      
      // Generate deterministic keys for the voter
      const voterKeys = await generateDeterministicKeys({
        voterID,
        electionParams: 'default-election-params',
        systemEntropy: 'system-entropy-2025',
        commitmentParams
      });
      
      console.log('Calling generateZKProof...');
      
      // Generate ZK proof
      const zkProof = await generateZKProof(
        vote,
        voterKeys,
        'default-election-params',
        (status: ZKProofGenerationStatus) => {
          set({ zkProofStatus: status });
        }
      );
        // Validate before storing
      const validation = await validateProofSubmissionReadiness(zkProof);
      if (!validation.isReady) {
        throw new Error(`Proof validation failed: ${validation.errors.join(', ')}`);
      }
      
      // Extract public verification data      // Generate public verification data
      const publicVerificationPackage = await generatePublicVerificationData(zkProof);
      
      // Submit complete ZK proof to backend
      try {
        const apiResult = await zkProofApi.submitCompleteZKProof(
          zkProof,
          publicVerificationPackage
        );

        if (!apiResult.success) {
          console.warn('Failed to submit ZK proof to backend:', apiResult.message);
        } else {
          console.log('✅ ZK proof submitted to backend successfully');
        }
      } catch (backendError) {
        console.warn('Backend ZK proof submission failed:', backendError);
        // Continue anyway - local verification is primary
      }
        set({ 
        zkProof,
        publicVerificationData: {
          verificationCode: zkProof.verificationCode,
          electionId: zkProof.electionId,
          timestamp: zkProof.timestamp,
          publicParameters: zkProof.publicParameters,
          verificationUrl: publicVerificationPackage.publicVerificationUrl,
          qrCode: publicVerificationPackage.qrCodeData,
          wasmVerified: zkProof.wasmProofData.generationMethod === 'pure-wasm'
        }
      });
      
      return zkProof;
        } catch (error) {
      console.error('ZK proof generation failed:', error);
      console.error('Error details:', {
        message: error instanceof Error ? error.message : 'Unknown error',
        stack: error instanceof Error ? error.stack : undefined,
        vote,
        voterID
      });
        set({ 
        zkProofStatus: { 
          status: 'error', 
          progress: 0, 
          currentStep: 'initializing',
          error: error instanceof Error ? error.message : 'Unknown error',
          wasmStatus: 'error'
        }
      });
      throw error;
    }
  },  verifyOwnProof: async (proof: ZKProofData): Promise<boolean> => {
    try {
      console.log('🔍 Starting detailed proof verification...');
      const validation = await validateProofSubmissionReadiness(proof);
      
      if (!validation.isReady) {
        console.log('❌ Proof failed readiness validation:', validation.errors);
        return false;
      }
      
      // Use enhanced verification with detailed logging
      const verificationResult = await verifyCompleteZKProofWithDetails(proof);
      
      // Generate public verification data for transparency
      const publicData = await generatePublicVerificationData(proof);
      console.log('📦 Public verification data generated:', {
        url: publicData.publicVerificationUrl,
        qrCodeLength: publicData.qrCodeData.length
      });
      
      return verificationResult.isValid;
    } catch (error) {
      console.error('❌ Proof verification failed:', error);
      return false;
    }
  },

  getPublicVerificationData: (): PublicVerificationData | null => {
    return get().publicVerificationData;
  },

  enforceSignleGeneration: (): void => {
    const state = get();
    if (state.zkProof) {
      // Clear any previous proof to enforce single generation
      set({ 
        zkProof: null, 
        publicVerificationData: null,
        zkProofStatus: { 
          status: 'idle', 
          progress: 0, 
          currentStep: 'initializing',
          wasmStatus: 'loading'
        }
      });
    }
  },

  setZKProofStatus: (status: ZKProofGenerationStatus): void => {
    set({ zkProofStatus: status });
  },
}));
